---
# Postfix
# TODO: add mail forwarding from root to external email

- name: "Install and configure Postfix mail transfer agent"
  become: true
  
  block:
    - name: "Check that expected variables have been passed"
      assert:
        that:
          - postfix__host is defined
          - postfix__ssl_crt is defined
          - postfix__ssl_key is defined

    - name: "Set Postfix option - type of configuration"
      debconf: 
        name: "postfix"
        question: "postfix/main_mailer_type"
        value: "Internet Site"
        vtype: "string"

    - name: "Set Postfix option - default host name"
      debconf: 
        name: "postfix"
        question: "postfix/mailname"
        value: "{{ postfix__host }}"
        vtype: "string"

    - name: "Install postfix"
      apt:
        name: "postfix"
        state: "present"
        update_cache: yes

    - name: "Upload Postfix configuration"
      template:
        src: "postfix.conf"
        dest: "/etc/postfix/main.cf"
      notify:
      - restart postfix