# Generated by Django 3.2 on 2021-07-02 14:57

from django.db import migrations, models
import quizzz.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_email_confirmed',
            field=models.BooleanField(default=False, help_text='Designates whether the user has confirmed their email address.', verbose_name='email confirmed'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=quizzz.users.models.LowercaseEmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
