# Generated by Django 3.2 on 2021-08-10 22:43

import django.contrib.auth.validators
from django.db import migrations
import quizzz.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=quizzz.users.models.LowercaseCharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Lower-case letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username'),
        ),
    ]
