export const LOGIN_REQUEST_START = "LOGIN_REQUEST_START";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_FAIL = "LOGIN_REQUEST_FAIL";

export const LOGOUT_REQUEST_START = "LOGOUT_REQUEST_START";
export const LOGOUT_REQUEST_SUCCESS = "LOGOUT_REQUEST_SUCCESS";
export const LOGOUT_REQUEST_FAIL = "LOGOUT_REQUEST_FAIL";

export const USER_REQUEST_START = "USER_REQUEST_START";
export const USER_REQUEST_SUCCESS = "USER_REQUEST_SUCCESS";
export const USER_REQUEST_FAIL = "USER_REQUEST_FAIL";