---

# ansible connection settings
ansible_user: vagrant
ansible_host: localhost
ansible_port: 2222
# ansible_python_interpreter: /usr/bin/python3    # no longer needed with 'focal'

ansible_ssh_private_key_file: "{{ inventory_dir | dirname | dirname | dirname }}/.vagrant/machines/default/virtualbox/private_key"
ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
app__git_push_ssh_command: >-
  ssh 
  -p {{ ansible_port }} 
  -o IdentityFile={{ ansible_ssh_private_key_file }} 
  {{ ansible_ssh_common_args }}